"use client";

import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { commerceApi } from "@/lib/api/commerce";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState, ErrorState, LoadingCard } from "@/components/feedback-states";
import { PageIntro } from "@/components/page-intro";
import { CustomerReference } from "@/components/customers/customer-reference";

export default function ReviewsPage() {
  const queryClient = useQueryClient();
  const reviews = useQuery({ queryKey: ["admin", "reviews"], queryFn: commerceApi.reviews });
  const moderate = useMutation({ mutationFn: ({ id, status }: { id: string; status: "APPROVED" | "REJECTED" }) => commerceApi.moderateReview(id, status), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["admin", "reviews"] }) });
  return <><PageIntro eyebrow="Catalog trust" title="Reviews" description="Moderate product feedback. Customer submissions are checked against a delivered or completed order before publication." />{reviews.isLoading ? <LoadingCard /> : reviews.isError ? <ErrorState title="Reviews unavailable" message="Catalog Service could not be reached." onRetry={() => void reviews.refetch()} /> : reviews.data?.content.length ? <Card className="overflow-hidden"><div className="divide-y divide-slate-100">{reviews.data.content.map((review) => <div key={review.id} className="flex flex-wrap items-start justify-between gap-5 p-5"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</p><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500">{review.status}</span>{review.verifiedPurchase ? <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Verified purchase</span> : null}</div><p className="mt-3 text-sm font-semibold text-slate-800">{review.title ?? "Untitled review"}</p><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">{review.comment}</p><div className="mt-5 grid gap-4 rounded-2xl border border-slate-100 bg-slate-50/70 p-4 sm:grid-cols-3"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400">Product</p><Link href={`/products/${review.productId}`} className="mt-1 block truncate text-sm font-semibold text-primary hover:underline">{review.productName ?? "View product details"}</Link><p className="mt-1 truncate font-mono text-[11px] text-slate-400">{review.sku ?? "Product-level review"}</p></div><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400">Order</p><Link href={`/orders/${review.orderId}`} className="mt-1 block truncate font-mono text-sm font-semibold text-primary hover:underline">{review.orderId}</Link><p className="mt-1 truncate font-mono text-[11px] text-slate-400">Item {review.orderItemId}</p></div><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-400">Customer</p>{review.customerId ? <div className="mt-1"><CustomerReference customerId={review.customerId} /></div> : <p className="mt-1 text-sm text-slate-500">Customer reference unavailable</p>}</div></div></div>{review.status === "PENDING" ? <div className="flex shrink-0 gap-2"><Button size="sm" onClick={() => moderate.mutate({ id: review.id, status: "APPROVED" })}>Approve</Button><Button size="sm" variant="destructive" onClick={() => moderate.mutate({ id: review.id, status: "REJECTED" })}>Reject</Button></div> : null}</div>)}</div></Card> : <EmptyState title="No reviews" message="Product reviews will appear here for moderation." />}</>;
}
