package com.shop.order.domain;

public enum OrderEventType {
    ORDER_CREATED,
    RESERVATION_REQUESTED,
    RESERVATION_CONFIRMED,
    RESERVATION_FAILED,
    ORDER_READY_FOR_PAYMENT,
    ITEM_CANCELLED,
    ORDER_PAID,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_STATE_CHANGED
}
