import Link from "next/link";
import { Boxes, History, MapPin, PackageCheck } from "lucide-react";
import { EmptyState } from "@/components/feedback-states";
import { FulfillmentStatusBadge } from "@/components/shipping/status-badges";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { CustomerProfile } from "@/lib/api/customer/types";
import type { FulfillmentDetail, FulfillmentHistoryEntry } from "@/lib/api/shipping/types";
import { formatDate, titleCase } from "@/lib/utils";

function Info({ label, value, mono, children }: { label: string; value?: string; mono?: boolean; children?: React.ReactNode }) {
  return <div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-slate-400">{label}</p>{children ?? <p className={`mt-2 break-words text-sm font-semibold text-slate-800 ${mono ? "font-mono" : ""}`}>{value ?? "—"}</p>}</div>;
}

export function FulfillmentOverview({ fulfillment, customer, canReadOrder, canReadCustomer }: { fulfillment: FulfillmentDetail; customer?: CustomerProfile; canReadOrder: boolean; canReadCustomer: boolean }) {
  const totalQuantity = fulfillment.items.reduce((total, item) => total + item.quantity, 0);
  const customerName = customer ? [customer.firstName, customer.lastName].filter(Boolean).join(" ").trim() || customer.email || "Unnamed customer" : "Customer profile unavailable";
  return <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Fulfillment overview</CardTitle><p className="mt-1 text-sm text-muted-foreground">Shipping owns this operational work record; Order remains authoritative for the commercial lifecycle.</p></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="Fulfillment ID" value={fulfillment.id} mono /><Info label="Status"><FulfillmentStatusBadge status={fulfillment.status} /></Info><Info label="Order">{canReadOrder ? <Link href={`/orders/${fulfillment.orderId}`} className="mt-2 block font-mono text-sm font-semibold text-primary hover:underline">{fulfillment.orderNumber}</Link> : <p className="mt-2 text-sm text-slate-500">Order link requires ORDER_READ.</p>}</Info><Info label="Customer">{canReadCustomer && customer ? <Link href={`/customers/${customer.id}`} className="mt-2 block text-sm font-semibold text-primary hover:underline">{customerName}</Link> : canReadCustomer ? <p className="mt-2 text-sm text-slate-500">Customer profile unavailable.</p> : <p className="mt-2 text-sm text-slate-500">Customer link requires CUSTOMER_READ.</p>}</Info><Info label="Item lines" value={String(fulfillment.items.length)} /><Info label="Total quantity" value={String(totalQuantity)} /><Info label="Shipment count" value={String(fulfillment.shipments.length)} /><Info label="Created" value={formatDate(fulfillment.createdAt)} /><Info label="Updated" value={formatDate(fulfillment.updatedAt)} /><Info label="Completed" value={formatDate(fulfillment.completedAt)} /></CardContent></Card><HistoricalAddress fulfillment={fulfillment} /></div>;
}

function HistoricalAddress({ fulfillment }: { fulfillment: FulfillmentDetail }) {
  const address = fulfillment.shippingAddress;
  return <Card><CardHeader><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary" /><div><CardTitle>Shipping address snapshot</CardTitle><p className="mt-1 text-sm text-muted-foreground">Copied from the historical Order address at fulfillment creation.</p></div></div></CardHeader><CardContent>{address ? <div className="space-y-2 text-sm text-slate-700"><p className="font-semibold">{address.recipientName ?? "Recipient not returned"}</p><p>{address.line1}{address.line2 ? `, ${address.line2}` : ""}</p><p>{[address.city, address.state, address.postalCode].filter(Boolean).join(", ")}</p><p>{address.country ?? "—"}{address.phone ? ` · ${address.phone}` : ""}</p>{address.landmark && <p className="text-slate-500">Landmark: {address.landmark}</p>}</div> : <p className="text-sm text-slate-500">Historical shipping address was not returned.</p>}</CardContent></Card>;
}

export function FulfillmentCustomerPanel({ customer, customerId, errorMessage, canReadCustomer }: { customer?: CustomerProfile; customerId: string; errorMessage?: string; canReadCustomer: boolean }) {
  const name = customer ? [customer.firstName, customer.lastName].filter(Boolean).join(" ").trim() || customer.email || "Unnamed customer" : undefined;
  return <Card><CardHeader><CardTitle>Customer</CardTitle><p className="mt-1 text-sm text-muted-foreground">Customer profile data is optional enrichment from Customer Service.</p></CardHeader><CardContent>{errorMessage ? <p className="text-sm text-amber-700">{errorMessage}</p> : <div className="grid gap-5 sm:grid-cols-3"><Info label="Customer">{canReadCustomer ? <Link href={customer ? `/customers/${customer.id}` : "#"} className="mt-2 block text-sm font-semibold text-primary hover:underline">{name ?? "Customer profile unavailable"}</Link> : <p className="mt-2 text-sm text-slate-500">Customer link requires CUSTOMER_READ.</p>}</Info><Info label="Email" value={customer?.email ?? "Not returned"} /><Info label="Auth user ID" value={customerId} mono /></div>}</CardContent></Card>;
}

export function FulfillmentItems({ fulfillment, canReadInventory }: { fulfillment: FulfillmentDetail; canReadInventory: boolean }) {
  if (!fulfillment.items.length) return <EmptyState title="No fulfillment items available" message="Shipping did not return any item snapshots for this fulfillment." />;
  return <Card><CardHeader><div className="flex items-center gap-2"><PackageCheck className="h-5 w-5 text-primary" /><div><CardTitle>Fulfillment items</CardTitle><p className="mt-1 text-sm text-muted-foreground">The API returns order-item quantities and exact Inventory Unit references. It does not return allocated/shipped counters.</p></div></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><caption className="sr-only">Fulfillment item references</caption><thead><tr className="border-y border-slate-100 text-xs font-semibold uppercase tracking-[0.1em] text-slate-400"><th className="px-5 py-3">Product snapshot</th><th className="px-3 py-3">SKU</th><th className="px-3 py-3">Ordered quantity</th><th className="px-3 py-3">Inventory units</th><th className="px-3 py-3">Order item</th></tr></thead><tbody>{fulfillment.items.map((item) => <tr className="table-row" key={item.id}><td className="px-5 py-4"><p className="font-semibold text-slate-800">{item.productNameSnapshot}</p><p className="mt-1 text-xs text-slate-400">Fulfillment item {item.id}</p></td><td className="px-3 py-4">{canReadInventory ? <Link href={`/inventory/stock/${encodeURIComponent(item.sku)}`} className="font-mono text-sm font-semibold text-primary hover:underline">{item.sku}</Link> : <span className="font-mono text-sm text-slate-700">{item.sku}</span>}</td><td className="px-3 py-4 text-sm font-semibold text-slate-700">{item.quantity}</td><td className="px-3 py-4">{item.inventoryUnitIds.length ? <div className="flex max-w-[24rem] flex-wrap gap-2">{item.inventoryUnitIds.map((unitId, index) => canReadInventory ? <Link href={`/inventory/units/${unitId}`} className="inline-flex items-center gap-1 rounded-lg bg-slate-100 px-2 py-1 font-mono text-xs font-semibold text-primary hover:bg-blue-50" key={unitId}><Boxes className="h-3 w-3" />{item.inventoryUnitCodes[index] ?? unitId}</Link> : <span className="rounded-lg bg-slate-100 px-2 py-1 font-mono text-xs text-slate-600" key={unitId}>{item.inventoryUnitCodes[index] ?? unitId}</span>)}</div> : <span className="text-sm text-slate-500">No physical unit references</span>}</td><td className="px-3 py-4 font-mono text-xs text-slate-600">{item.orderItemId}</td></tr>)}</tbody></table></div></CardContent></Card>;
}

export function FulfillmentShipments({ fulfillment }: { fulfillment: FulfillmentDetail }) {
  if (!fulfillment.shipments.length) return <Card><CardHeader><CardTitle>Shipments</CardTitle></CardHeader><CardContent><p className="text-sm text-slate-500">No shipments have been created for this fulfillment.</p></CardContent></Card>;
  return <Card><CardHeader><CardTitle>Shipments</CardTitle><p className="mt-1 text-sm text-muted-foreground">One fulfillment may contain multiple shipments.</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><caption className="sr-only">Fulfillment shipments</caption><thead><tr className="border-y border-slate-100 text-xs font-semibold uppercase tracking-[0.1em] text-slate-400"><th className="px-5 py-3">Shipment</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Carrier</th><th className="px-3 py-3">Tracking</th><th className="px-3 py-3">Created</th></tr></thead><tbody>{fulfillment.shipments.map((shipment) => <tr className="table-row" key={shipment.id}><td className="px-5 py-4"><Link href={`/shipments/${shipment.id}`} className="font-mono text-sm font-semibold text-primary hover:underline">{shipment.shipmentNumber}</Link><p className="mt-1 font-mono text-[10px] text-slate-400">{shipment.id}</p></td><td className="px-3 py-4"><FulfillmentShipmentStatus status={shipment.status} /></td><td className="px-3 py-4 text-sm text-slate-600">{shipment.carrier}</td><td className="px-3 py-4 font-mono text-xs text-slate-600">{shipment.trackingNumber ?? "—"}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(shipment.createdAt)}</td></tr>)}</tbody></table></div></CardContent></Card>;
}

function FulfillmentShipmentStatus({ status }: { status: FulfillmentDetail["shipments"][number]["status"] }) {
  return <Badge variant={status === "DELIVERED" ? "success" : status === "CANCELLED" || status === "FAILED" ? "danger" : status === "OUT_FOR_DELIVERY" ? "warning" : "default"}>{titleCase(status)}</Badge>;
}

export function FulfillmentHistoryTimeline({ entries }: { entries: FulfillmentHistoryEntry[] }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><History className="h-5 w-5 text-primary" /><div><CardTitle>Fulfillment history</CardTitle><p className="mt-1 text-sm text-muted-foreground">Append-only operational transitions from Shipping Service.</p></div></div></CardHeader><CardContent>{entries.length ? <ol className="space-y-4" aria-label="Fulfillment history">{[...entries].reverse().map((entry) => <li className="rounded-2xl border border-slate-100 p-4" key={entry.id}><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold text-slate-800">{entry.fromStatus ? `${titleCase(entry.fromStatus)} → ` : ""}{titleCase(entry.toStatus)}</p><time className="text-xs text-slate-400" dateTime={entry.createdAt}>{formatDate(entry.createdAt)}</time></div><div className="mt-2 flex flex-wrap gap-2"><Badge variant="muted">{titleCase(entry.eventType)}</Badge>{entry.referenceId && <Badge variant="outline">{entry.referenceId}</Badge>}</div>{entry.notes && <p className="mt-2 text-sm leading-6 text-slate-600">{entry.notes}</p>}</li>)}</ol> : <p className="text-sm text-slate-500">No fulfillment history available.</p>}</CardContent></Card>;
}
