import Link from "next/link";
import { Boxes, History, MapPin, PackageSearch, Route, Truck } from "lucide-react";
import { EmptyState } from "@/components/feedback-states";
import { ShipmentStatusBadge } from "@/components/shipping/status-badges";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { CustomerProfile } from "@/lib/api/customer/types";
import type { ShipmentDetail, ShipmentHistoryEntry, TrackingResponse } from "@/lib/api/shipping/types";
import { formatCurrency, formatDate, titleCase } from "@/lib/utils";

function Info({ label, value, mono, children }: { label: string; value?: string; mono?: boolean; children?: React.ReactNode }) {
  return <div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-slate-400">{label}</p>{children ?? <p className={`mt-2 break-words text-sm font-semibold text-slate-800 ${mono ? "font-mono" : ""}`}>{value ?? "—"}</p>}</div>;
}

export function ShipmentOverview({ shipment, canReadOrder }: { shipment: ShipmentDetail; canReadOrder: boolean }) {
  return <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card><CardHeader><CardTitle>Shipment overview</CardTitle><p className="mt-1 text-sm text-muted-foreground">Shipping owns transportation state and safe carrier references.</p></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="Shipment number" value={shipment.shipmentNumber} mono /><Info label="Status"><ShipmentStatusBadge status={shipment.status} /></Info><Info label="Order">{canReadOrder ? <Link href={`/orders/${shipment.orderId}`} className="mt-2 block font-mono text-sm font-semibold text-primary hover:underline">{shipment.orderNumber}</Link> : <p className="mt-2 text-sm text-slate-500">Order link requires ORDER_READ.</p>}</Info><Info label="Fulfillment"><Link href={`/fulfillments/${shipment.fulfillmentId}`} className="mt-2 block font-mono text-sm font-semibold text-primary hover:underline">{shipment.fulfillmentId}</Link></Info><Info label="Carrier" value={shipment.carrier} /><Info label="Service level" value={shipment.serviceLevel} /><Info label="Tracking number" value={shipment.trackingNumber ?? "Not returned"} mono /><Info label="Provider shipment ID" value={shipment.providerShipmentId ?? "Not returned"} mono /><Info label="Label reference" value={shipment.labelReference ?? "Not returned"} mono /><Info label="Package count" value={String(shipment.packageCount)} /><Info label="Shipping cost" value={formatCurrency(shipment.shippingCost, shipment.currency)} /><Info label="Currency" value={shipment.currency} /><Info label="Created" value={formatDate(shipment.createdAt)} /><Info label="Updated" value={formatDate(shipment.updatedAt)} /><Info label="Shipped" value={formatDate(shipment.shippedAt)} /><Info label="Delivered" value={formatDate(shipment.deliveredAt)} /><Info label="Cancelled" value={formatDate(shipment.cancelledAt)} /></CardContent></Card><Card><CardHeader><CardTitle>Carrier operations</CardTitle><p className="mt-1 text-sm text-muted-foreground">Only non-secret provider references returned by Shipping are shown.</p></CardHeader><CardContent className="space-y-4"><div className="flex items-start gap-3 rounded-2xl bg-slate-50 p-4"><Truck className="mt-0.5 h-5 w-5 text-primary" /><div><p className="text-sm font-semibold text-slate-800">{shipment.carrier}</p><p className="mt-1 text-sm text-slate-500">{shipment.serviceLevel}</p></div></div>{shipment.orderNotificationPending && <div role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800">The Shipping Service has not confirmed its latest Order notification. Order status remains owned by Order Service.</div>}<p className="text-xs leading-5 text-slate-500">Package detail and label download endpoints are not part of the current Shipping API, so no package dimensions or label URL is invented here.</p></CardContent></Card></div>;
}

export function ShipmentCustomerPanel({ customer, customerId, errorMessage, canReadCustomer }: { customer?: CustomerProfile; customerId: string; errorMessage?: string; canReadCustomer: boolean }) {
  const name = customer ? [customer.firstName, customer.lastName].filter(Boolean).join(" ").trim() || customer.email || "Unnamed customer" : undefined;
  return <Card><CardHeader><CardTitle>Customer</CardTitle><p className="mt-1 text-sm text-muted-foreground">Customer profile data is read from Customer Service; Shipping keeps the ownership reference.</p></CardHeader><CardContent>{errorMessage ? <p className="text-sm text-amber-700">{errorMessage}</p> : <div className="grid gap-5 sm:grid-cols-2"><Info label="Customer">{canReadCustomer ? <Link href={customer ? `/customers/${customer.id}` : "#"} className="mt-2 block text-sm font-semibold text-primary hover:underline">{name ?? "Customer profile unavailable"}</Link> : <p className="mt-2 text-sm text-slate-500">Customer link requires CUSTOMER_READ.</p>}</Info><Info label="Email" value={customer?.email ?? "Not returned"} /><Info label="Auth user ID" value={customerId} mono /></div>}</CardContent></Card>;
}

export function ShipmentItems({ shipment, canReadInventory }: { shipment: ShipmentDetail; canReadInventory: boolean }) {
  if (!shipment.items.length) return <EmptyState title="No shipment items available" message="Shipping did not return any item references for this shipment." />;
  return <Card><CardHeader><div className="flex items-center gap-2"><PackageSearch className="h-5 w-5 text-primary" /><div><CardTitle>Shipment items</CardTitle><p className="mt-1 text-sm text-muted-foreground">Each row is a Shipping reference to an Order Item and, when itemized, one physical Inventory Unit.</p></div></div></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><caption className="sr-only">Shipment item references</caption><thead><tr className="border-y border-slate-100 text-xs font-semibold uppercase tracking-[0.1em] text-slate-400"><th className="px-5 py-3">Product snapshot</th><th className="px-3 py-3">SKU</th><th className="px-3 py-3">Quantity</th><th className="px-3 py-3">Inventory unit</th><th className="px-3 py-3">Order item</th></tr></thead><tbody>{shipment.items.map((item) => <tr className="table-row" key={item.id}><td className="px-5 py-4"><p className="font-semibold text-slate-800">{item.productNameSnapshot}</p><p className="mt-1 text-xs text-slate-400">Shipment item {item.id}</p></td><td className="px-3 py-4">{canReadInventory ? <Link href={`/inventory/stock/${encodeURIComponent(item.sku)}`} className="font-mono text-sm font-semibold text-primary hover:underline">{item.sku}</Link> : <span className="font-mono text-sm text-slate-700">{item.sku}</span>}</td><td className="px-3 py-4 text-sm font-semibold text-slate-700">{item.quantity}</td><td className="px-3 py-4">{item.inventoryUnitId ? canReadInventory ? <Link href={`/inventory/units/${item.inventoryUnitId}`} className="inline-flex items-center gap-1 font-mono text-xs font-semibold text-primary hover:underline"><Boxes className="h-3.5 w-3.5" />{item.inventoryUnitId}</Link> : <span className="font-mono text-xs text-slate-600">{item.inventoryUnitId}</span> : <span className="text-sm text-slate-500">No physical unit reference</span>}</td><td className="px-3 py-4 font-mono text-xs text-slate-600">{item.orderItemId}</td></tr>)}</tbody></table></div><div className="border-t border-slate-100 px-5 py-3 text-xs leading-5 text-slate-500">Inventory Unit state remains authoritative in Inventory Service. Shipping only links to the returned physical unit reference.</div></CardContent></Card>;
}

export function ShipmentTrackingPanel({ tracking, isLoading, errorMessage, onRetry }: { tracking?: TrackingResponse; isLoading: boolean; errorMessage?: string; onRetry?: () => void }) {
  if (isLoading) return <Card><CardHeader><CardTitle>Tracking</CardTitle></CardHeader><CardContent><div className="h-28 animate-pulse rounded-2xl bg-slate-100" /></CardContent></Card>;
  if (errorMessage) return <Card><CardHeader><CardTitle>Tracking</CardTitle></CardHeader><CardContent><div role="alert" className="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 sm:flex-row sm:items-center sm:justify-between"><span>{errorMessage}</span>{onRetry && <button type="button" className="font-semibold underline underline-offset-4" onClick={onRetry}>Retry</button>}</div></CardContent></Card>;
  if (!tracking || !tracking.events.length) return <Card><CardHeader><div className="flex items-center gap-2"><Route className="h-5 w-5 text-primary" /><CardTitle>Tracking</CardTitle></div></CardHeader><CardContent><p className="text-sm text-slate-500">No tracking events available.</p></CardContent></Card>;
  const events = [...tracking.events].sort((left, right) => new Date(right.occurredAt).getTime() - new Date(left.occurredAt).getTime());
  return <Card><CardHeader><div className="flex items-center gap-2"><Route className="h-5 w-5 text-primary" /><div><CardTitle>Tracking</CardTitle><p className="mt-1 text-sm text-muted-foreground">Normalized carrier events from Shipping Service.</p></div></div></CardHeader><CardContent><div className="grid gap-5 sm:grid-cols-4"><Info label="Carrier" value={tracking.carrier} /><Info label="Tracking number" value={tracking.trackingNumber ?? "Not returned"} mono /><Info label="Current status"><ShipmentStatusBadge status={tracking.currentStatus} /></Info><Info label="Estimated delivery" value={formatDate(tracking.estimatedDeliveryAt)} /></div><ol className="mt-6 space-y-4" aria-label="Tracking event timeline">{events.map((event, index) => <li className="relative flex gap-4" key={event.id}>{index < events.length - 1 && <span className="absolute left-[0.4375rem] top-3 h-full w-px bg-slate-200" aria-hidden="true" />}<span className="relative mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-primary ring-4 ring-blue-50" aria-hidden="true" /><div className="min-w-0 flex-1 rounded-2xl border border-slate-100 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-slate-800">{titleCase(event.eventType)}</p><p className="mt-1 text-xs text-slate-500">{event.eventStatus}</p></div><time className="text-xs text-slate-400" dateTime={event.occurredAt}>{formatDate(event.occurredAt)}</time></div>{event.eventLocation && <p className="mt-3 flex items-center gap-1 text-sm text-slate-600"><MapPin className="h-3.5 w-3.5" />{event.eventLocation}</p>}{event.description && <p className="mt-2 text-sm leading-6 text-slate-600">{event.description}</p>}</div></li>)}</ol></CardContent></Card>;
}

export function ShipmentHistoryTimeline({ entries }: { entries: ShipmentHistoryEntry[] }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><History className="h-5 w-5 text-primary" /><div><CardTitle>Shipment history</CardTitle><p className="mt-1 text-sm text-muted-foreground">Append-only lifecycle history returned by Shipping Service.</p></div></div></CardHeader><CardContent>{entries.length ? <ol className="space-y-4" aria-label="Shipment history">{[...entries].reverse().map((entry) => <li className="rounded-2xl border border-slate-100 p-4" key={entry.id}><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold text-slate-800">{entry.fromStatus ? `${titleCase(entry.fromStatus)} → ` : ""}{titleCase(entry.toStatus)}</p><time className="text-xs text-slate-400" dateTime={entry.createdAt}>{formatDate(entry.createdAt)}</time></div><div className="mt-2 flex flex-wrap gap-2"><Badge variant="muted">{titleCase(entry.eventType)}</Badge>{entry.carrierEventId && <Badge variant="outline">Carrier event {entry.carrierEventId}</Badge>}</div>{entry.notes && <p className="mt-2 text-sm leading-6 text-slate-600">{entry.notes}</p>}</li>)}</ol> : <p className="text-sm text-slate-500">No shipment history available.</p>}</CardContent></Card>;
}

export function ShipmentFulfillmentContext({ fulfillmentId, status, errorMessage }: { fulfillmentId: string; status?: string; errorMessage?: string }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><Truck className="h-5 w-5 text-primary" /><CardTitle>Fulfillment</CardTitle></div></CardHeader><CardContent>{errorMessage ? <p className="text-sm text-amber-700">{errorMessage}</p> : <div className="grid gap-5 sm:grid-cols-2"><Info label="Fulfillment ID"><Link href={`/fulfillments/${fulfillmentId}`} className="mt-2 block font-mono text-sm font-semibold text-primary hover:underline">{fulfillmentId}</Link></Info><Info label="Status" value={status ? titleCase(status) : "Not returned"} /></div>}</CardContent></Card>;
}

export function ShipmentOrderContext({ orderId, orderNumber, status, errorMessage, canReadOrder }: { orderId: string; orderNumber: string; status?: string; errorMessage?: string; canReadOrder: boolean }) {
  return <Card><CardHeader><CardTitle>Order</CardTitle><p className="mt-1 text-sm text-muted-foreground">Order Service owns order lifecycle and historical commercial data.</p></CardHeader><CardContent>{errorMessage ? <p className="text-sm text-amber-700">{errorMessage}</p> : <div className="grid gap-5 sm:grid-cols-3"><Info label="Order number">{canReadOrder ? <Link href={`/orders/${orderId}`} className="mt-2 block font-mono text-sm font-semibold text-primary hover:underline">{orderNumber}</Link> : <p className="mt-2 text-sm text-slate-500">Order link requires ORDER_READ.</p>}</Info><Info label="Order ID" value={orderId} mono /><Info label="Order status" value={status ? titleCase(status) : "Not returned"} /></div>}</CardContent></Card>;
}
