"use client";

import Link from "next/link";
import { useQueries } from "@tanstack/react-query";
import { Cuboid } from "lucide-react";
import type { ProductVariant } from "@/lib/types";
import { inventoryApi } from "@/lib/api/inventory";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { InventoryServiceUnavailable } from "@/components/inventory/inventory-common";

export function ProductInventoryPanel({ variants }: { variants: ProductVariant[] }) { const results = useQueries({ queries: variants.map((variant) => ({ queryKey: ["inventory", "product-sku", variant.sku], queryFn: () => inventoryApi.stock({ page: 0, size: 100, sort: "sku,asc", sku: variant.sku }), staleTime: 30_000 })) }); const anyError = results.some((result) => result.isError); return <Card><CardHeader><div className="flex items-center gap-2"><Cuboid className="h-5 w-5 text-primary" /><div><CardTitle>Inventory</CardTitle><p className="mt-1 text-sm text-muted-foreground">SKU-level availability joined from the Inventory service.</p></div></div></CardHeader><CardContent>{anyError ? <InventoryServiceUnavailable /> : <div className="space-y-4">{variants.map((variant, index) => { const result = results[index]; const rows = result.data?.content ?? []; return <div className="rounded-2xl border border-slate-100 p-4" key={variant.id}><div className="flex items-start justify-between gap-3"><div><Link href={`/inventory/stock/${encodeURIComponent(variant.sku)}`} className="font-mono text-sm font-semibold text-primary hover:underline">{variant.sku}</Link><p className="mt-1 text-xs text-slate-400">Sellable configuration</p></div><span className="text-xs font-semibold text-slate-500">{rows.reduce((total, row) => total + row.available, 0)} available</span></div>{rows.length === 0 ? <p className="mt-3 text-sm text-slate-400">No inventory records for this SKU.</p> : <div className="mt-3 space-y-2">{rows.map((row, rowIndex) => <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5" key={`${row.sku}-${row.location?.id ?? rowIndex}`}><span className="text-sm text-slate-600">{row.location?.name ?? row.location?.code ?? "Location stock"}</span><span className="text-sm font-semibold text-slate-700">{row.available} available · {row.reserved} reserved</span></div>)}</div>}{result.isFetching && <p className="mt-2 text-xs text-slate-400">Refreshing inventory…</p>}</div>; })}</div>}</CardContent></Card>; }
