"use client";

import Link from "next/link";
import { ArrowLeft, History } from "lucide-react";
import { useParams } from "next/navigation";
import { PageIntro } from "@/components/page-intro";
import { InventoryServiceUnavailable } from "@/components/inventory/inventory-common";
import { UnitStatusBadge } from "@/components/inventory/status-badges";
import { LoadingCard } from "@/components/feedback-states";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useInventoryUnit } from "@/lib/queries";
import { formatDate } from "@/lib/utils";

export default function UnitDetailPage() { const params = useParams<{ id: string }>(); const unit = useInventoryUnit(params.id); if (unit.isLoading) return <LoadingCard rows={6} />; if (unit.isError || !unit.data) return <InventoryServiceUnavailable error={unit.error} onRetry={() => void unit.refetch()} />; const item = unit.data; return <><div className="mb-5"><Button asChild variant="ghost" size="sm"><Link href="/inventory/units"><ArrowLeft className="h-4 w-4" />Back to inventory units</Link></Button></div><PageIntro eyebrow="Inventory unit detail" title={item.unitCode} description="One physical inventory item, tracked separately from the sellable SKU." /><div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><Card><CardHeader><CardTitle>Identity</CardTitle><p className="mt-1 text-sm text-muted-foreground">SKU is the sellable configuration. Unit ID identifies this physical item.</p></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="Inventory Unit ID" value={item.id} mono /><Info label="Unit code" value={item.unitCode} mono /><Info label="SKU" value={item.sku} link={`/inventory/stock/${encodeURIComponent(item.sku)}`} mono /><Info label="Product" value={item.productName ?? "Catalog lookup unavailable"} /><Info label="Variant" value="Catalog variant lookup by SKU" /><Info label="Location" value={`${item.location.code} · ${item.location.name}`} /><Info label="Status" value=""><UnitStatusBadge status={item.status} /></Info><Info label="Serial number" value={item.serialNumber ?? "—"} /><Info label="IMEI" value={item.imei ?? "—"} /><Info label="Barcode" value={item.barcode ?? "—"} /><Info label="Received at" value={formatDate(item.receivedAt)} /><Info label="Sold at" value={item.soldAt ? formatDate(item.soldAt) : "—"} /></CardContent></Card><Card><CardHeader><div className="flex items-center gap-2"><History className="h-5 w-5 text-primary" /><div><CardTitle>Movement history</CardTitle><p className="mt-1 text-sm text-muted-foreground">Every transfer or status change remains auditable.</p></div></div></CardHeader><CardContent>{item.movements?.length ? <div className="space-y-4">{item.movements.map((movement) => <div className="rounded-2xl border border-slate-100 p-4" key={movement.id}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-slate-700">{movement.referenceType}</p><p className="text-xs text-slate-400">{formatDate(movement.createdAt)}</p></div><p className="mt-2 text-sm text-slate-600">{movement.fromLocation?.code ?? "—"} → {movement.toLocation?.code ?? "—"}</p><p className="mt-1 text-xs text-slate-400">{movement.fromStatus ?? "—"} → {movement.toStatus ?? "—"}{movement.referenceId ? ` · ${movement.referenceId}` : ""}</p></div>)}</div> : <p className="text-sm text-slate-500">No movement history available.</p>}</CardContent></Card></div></>; }

function Info({ label, value, mono, link, children }: { label: string; value: string; mono?: boolean; link?: string; children?: React.ReactNode }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-slate-400">{label}</p>{children ?? (link ? <Link href={link} className={`mt-2 block text-sm font-semibold text-primary hover:underline ${mono ? "font-mono" : ""}`}>{value}</Link> : <p className={`mt-2 text-sm font-semibold text-slate-800 ${mono ? "font-mono" : ""}`}>{value}</p>)}</div>; }
