"use client";

import Link from "next/link";
import { ArrowRight, HeartHandshake, Leaf, PackageCheck, Sparkles } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { catalogApi } from "@/lib/api/catalog";
import { ProductGrid } from "@/components/product-card";
import { EmptyState, ErrorState, ProductSkeletonGrid } from "@/components/feedback";

export default function HomePage() {
  const categories = useQuery({ queryKey: ["categories", "root"], queryFn: () => catalogApi.listCategories() });
  const products = useQuery({ queryKey: ["products", "featured"], queryFn: () => catalogApi.listProducts({ page: 0, size: 8, sort: "createdAt,desc" }) });
  return <>
    <section className="page-shell pt-8 md:pt-12"><div className="relative overflow-hidden rounded-[2rem] bg-ink px-7 py-14 text-white md:px-14 md:py-24"><div className="absolute -right-24 -top-32 h-80 w-80 rounded-full bg-coral/30 blur-3xl" /><div className="absolute -bottom-32 left-1/3 h-72 w-72 rounded-full bg-moss/50 blur-3xl" /><div className="relative max-w-2xl"><p className="eyebrow text-sage">The everyday, elevated</p><h1 className="mt-5 font-display text-4xl font-semibold leading-[1.05] tracking-tight md:text-7xl">Good things for the way you live.</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/70 md:text-lg">Discover a considered collection of useful, beautiful pieces — chosen to make ordinary moments feel a little more yours.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="inline-flex min-h-12 items-center rounded-full bg-coral px-6 text-sm font-bold text-white transition hover:bg-[#d66d4d]">Shop the collection <ArrowRight className="ml-2 h-4 w-4" /></Link><Link href="/categories" className="inline-flex min-h-12 items-center rounded-full border border-white/25 px-6 text-sm font-bold text-white transition hover:bg-white/10">Explore categories</Link></div></div></div></section>
    <section className="page-shell section-space"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Find your next favorite</p><h2 className="mt-3 font-display text-3xl font-bold tracking-tight md:text-4xl">Shop by category</h2></div><Link href="/categories" className="hidden items-center gap-2 text-sm font-bold text-moss hover:text-ink sm:flex">View all <ArrowRight className="h-4 w-4" /></Link></div>{categories.isLoading ? <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4"><div className="h-40 animate-pulse rounded-3xl bg-ink/10" /><div className="h-40 animate-pulse rounded-3xl bg-ink/10" /><div className="h-40 animate-pulse rounded-3xl bg-ink/10" /><div className="h-40 animate-pulse rounded-3xl bg-ink/10" /></div> : categories.isError ? <div className="mt-8"><ErrorState message="Categories are temporarily unavailable." retry={() => void categories.refetch()} /></div> : categories.data?.length ? <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4">{categories.data.slice(0, 8).map((category, index) => <Link key={category.id} href={`/categories/${encodeURIComponent(category.slug)}`} className={`group flex min-h-40 flex-col justify-between rounded-3xl p-5 transition hover:-translate-y-1 hover:shadow-soft ${index % 3 === 0 ? "bg-sage" : index % 3 === 1 ? "bg-[#f3dfd5]" : "bg-[#e8e4d5]"}`}><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/60 text-moss"><Sparkles className="h-5 w-5" /></span><span className="flex items-center justify-between gap-2 font-display text-lg font-bold text-ink">{category.name}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div> : <div className="mt-8"><EmptyState title="Categories are coming soon" message="Browse the full collection while the catalogue grows." /></div>}</section>
    <section className="bg-white"><div className="page-shell section-space"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">A fresh perspective</p><h2 className="mt-3 font-display text-3xl font-bold tracking-tight md:text-4xl">New in the collection</h2></div><Link href="/products" className="hidden items-center gap-2 text-sm font-bold text-moss hover:text-ink sm:flex">Shop all <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-8">{products.isLoading ? <ProductSkeletonGrid /> : products.isError ? <ErrorState message="The collection is temporarily unavailable." retry={() => void products.refetch()} /> : products.data?.content.length ? <ProductGrid products={products.data.content} /> : <EmptyState title="The collection is taking shape" message="There are no published products to show yet." />}</div></div></section>
    <section className="page-shell section-space"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-3xl bg-sage p-7"><Leaf className="h-7 w-7 text-moss" /><h2 className="mt-8 font-display text-xl font-bold">Chosen with care</h2><p className="mt-2 text-sm leading-6 text-ink/65">A small, intentional selection instead of endless scrolling.</p></div><div className="rounded-3xl bg-[#f3dfd5] p-7"><PackageCheck className="h-7 w-7 text-coral" /><h2 className="mt-8 font-display text-xl font-bold">Clear at every step</h2><p className="mt-2 text-sm leading-6 text-ink/65">Current prices, availability checks, and order updates you can trust.</p></div><div className="rounded-3xl bg-[#e8e4d5] p-7"><HeartHandshake className="h-7 w-7 text-moss" /><h2 className="mt-8 font-display text-xl font-bold">Made for real life</h2><p className="mt-2 text-sm leading-6 text-ink/65">A calm, accessible shopping experience on every screen.</p></div></div></section>
  </>;
}
