import Link from "next/link";
import { Activity, CreditCard, ExternalLink, History, UserRound } from "lucide-react";
import { PaymentActions } from "@/components/payments/payment-actions";
import { PaymentAttemptStatusBadge, PaymentStatusBadge, RefundStatusBadge } from "@/components/payments/payment-status-badge";
import { CustomerReference } from "@/components/customers/customer-reference";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Payment, PaymentAttempt, PaymentRefund } from "@/lib/api/payment/types";
import type { CustomerProfile } from "@/lib/api/customer/types";
import type { OrderDetail } from "@/lib/api/order/types";
import { formatCurrency, formatDate, titleCase } from "@/lib/utils";

export function PaymentOverview({ payment, order }: { payment: Payment; order?: OrderDetail }) {
  const remaining = Math.max(0, payment.amount - payment.refundedAmount);
  return <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card><CardHeader><CardTitle>Overview</CardTitle><p className="mt-1 text-sm text-muted-foreground">Payment Service is authoritative for this payment, collection state, provider state, and refund totals.</p></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="Payment ID" value={payment.id} mono /><Info label="Status"><PaymentStatusBadge status={payment.status} /></Info><Info label="Order"><Link href={`/orders/${payment.orderId}`} className="mt-2 block font-mono text-sm font-semibold text-primary hover:underline">{order?.orderNumber ?? payment.orderId}</Link></Info><Info label="Customer"><CustomerReference customerId={payment.customerId} /></Info><Info label="Payment method" value={payment.paymentMethod.replaceAll("_", " ")} /><Info label="Amount" value={formatCurrency(payment.amount, payment.currency)} /><Info label="Currency" value={payment.currency} /><Info label="Created" value={formatDate(payment.createdAt)} /><Info label="Updated" value={formatDate(payment.updatedAt)} /><Info label="Authorized" value={formatDate(payment.authorizedAt)} /><Info label="Captured / collected" value={formatDate(payment.capturedAt)} /><Info label="Refunded amount" value={formatCurrency(payment.refundedAmount, payment.currency)} /><Info label="Remaining refundable" value={formatCurrency(remaining, payment.currency)} /></CardContent></Card><PaymentFinancialSummary payment={payment} /></div>;
}

function PaymentFinancialSummary({ payment }: { payment: Payment }) {
  return <Card><CardHeader><CardTitle>Payment actions</CardTitle><p className="mt-1 text-sm text-muted-foreground">Available actions are derived from payment state and Auth permissions.</p></CardHeader><CardContent className="space-y-5"><div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><span className="text-sm text-slate-500">Payment amount</span><span className="font-semibold text-slate-800">{formatCurrency(payment.amount, payment.currency)}</span></div><div className="mt-3 flex items-center justify-between gap-4"><span className="text-sm text-slate-500">Refunded</span><span className="font-semibold text-slate-800">{formatCurrency(payment.refundedAmount, payment.currency)}</span></div><div className="mt-3 flex items-center justify-between gap-4 border-t border-slate-200 pt-3"><span className="text-sm font-semibold text-slate-700">Remaining</span><span className="font-bold text-slate-950">{formatCurrency(Math.max(0, payment.amount - payment.refundedAmount), payment.currency)}</span></div></div><PaymentActions payment={payment} /></CardContent></Card>;
}

function Info({ label, value, mono, children }: { label: string; value?: string; mono?: boolean; children?: React.ReactNode }) {
  return <div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-slate-400">{label}</p>{children ?? <p className={`mt-2 break-all text-sm font-semibold text-slate-800 ${mono ? "font-mono" : ""}`}>{value}</p>}</div>;
}

export function PaymentOrderPanel({ payment, order, errorMessage }: { payment: Payment; order?: OrderDetail; errorMessage?: string }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><ExternalLink className="h-5 w-5 text-primary" /><div><CardTitle>Order</CardTitle><p className="mt-1 text-sm text-muted-foreground">Order state and totals remain owned by Order Service.</p></div></div></CardHeader><CardContent>{order ? <div className="grid gap-4 sm:grid-cols-3"><Info label="Order number"><Link href={`/orders/${order.id}`} className="mt-2 block font-semibold text-primary hover:underline">{order.orderNumber}</Link></Info><Info label="Order status"><Badge variant={order.status === "CANCELLED" || order.status === "FAILED" ? "danger" : "muted"}>{titleCase(order.status)}</Badge></Info><Info label="Order total" value={formatCurrency(order.totalAmount, order.currency)} /></div> : <div className="flex flex-col gap-3 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>{errorMessage ?? `Order reference: ${payment.orderId}`}</span><Link href={`/orders/${payment.orderId}`} className="inline-flex items-center gap-1 font-semibold text-primary hover:underline">Open order <ExternalLink className="h-3.5 w-3.5" /></Link></div>}</CardContent></Card>;
}

export function PaymentCustomerPanel({ payment, customer, errorMessage }: { payment: Payment; customer?: CustomerProfile; errorMessage?: string }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-primary" /><div><CardTitle>Customer</CardTitle><p className="mt-1 text-sm text-muted-foreground">Profile data is loaded from Customer Service when the operator has CUSTOMER_READ.</p></div></div></CardHeader><CardContent>{customer ? <div className="grid gap-4 sm:grid-cols-3"><Info label="Name"><Link href={`/customers/${customer.id}`} className="mt-2 block font-semibold text-primary hover:underline">{`${customer.firstName ?? ""} ${customer.lastName ?? ""}`.trim() || customer.email || "Unnamed customer"}</Link></Info><Info label="Email" value={customer.email ?? "Not available"} /><Info label="Profile"><Link href={`/customers/${customer.id}`} className="mt-2 inline-flex items-center gap-1 font-semibold text-primary hover:underline">View customer <ExternalLink className="h-3.5 w-3.5" /></Link></Info></div> : <div>{errorMessage && <p className="mb-2 text-sm text-slate-500">{errorMessage}</p>}<CustomerReference customerId={payment.customerId} /></div>}</CardContent></Card>;
}

export function PaymentAttempts({ attempts }: { attempts: PaymentAttempt[] }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-primary" /><div><CardTitle>Payment attempts</CardTitle><p className="mt-1 text-sm text-muted-foreground">Every provider attempt is retained, including failed attempts.</p></div></div></CardHeader><CardContent className="p-0">{attempts.length === 0 ? <p className="p-5 text-sm text-slate-500">No payment attempts.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left"><caption className="sr-only">Payment attempts</caption><thead><tr className="border-y border-slate-100 text-xs font-semibold uppercase tracking-[0.1em] text-slate-400"><th className="px-5 py-3">Attempt</th><th className="px-3 py-3">Provider</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Amount</th><th className="px-3 py-3">Provider payment ID</th><th className="px-3 py-3">Failure</th><th className="px-3 py-3">Started</th><th className="px-3 py-3">Completed</th></tr></thead><tbody>{attempts.map((attempt) => <tr className="table-row" key={attempt.id}><td className="px-5 py-4 text-sm font-semibold text-slate-800">#{attempt.attemptNumber}</td><td className="px-3 py-4 text-sm text-slate-700">{attempt.provider}</td><td className="px-3 py-4"><PaymentAttemptStatusBadge status={attempt.status} /></td><td className="px-3 py-4 text-right text-sm font-semibold text-slate-800">{formatCurrency(attempt.amount, attempt.currency)}</td><td className="px-3 py-4 font-mono text-xs text-slate-600">{attempt.providerPaymentId ?? "—"}</td><td className="px-3 py-4 text-sm text-rose-700">{attempt.failureCode ?? attempt.failureMessage ?? "—"}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(attempt.startedAt)}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(attempt.completedAt)}</td></tr>)}</tbody></table></div>}</CardContent></Card>;
}

export function PaymentGatewayPanel({ payment }: { payment: Payment }) {
  const cod = payment.paymentMethod === "CASH_ON_DELIVERY";
  return <Card><CardHeader><div className="flex items-center gap-2"><CreditCard className="h-5 w-5 text-primary" /><div><CardTitle>{cod ? "Gateway information" : "Gateway information"}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{cod ? "COD is collected at delivery and does not create a third-party gateway session." : "Safe provider references only. Checkout credentials and payment instrument data are not displayed."}</p></div></div></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><Info label="Provider" value={payment.provider ?? "No gateway"} /><Info label="Provider order ID" value={payment.providerOrderId ?? "Not returned"} mono /><Info label="Provider payment ID" value={payment.providerPaymentId ?? "Not returned"} mono /></CardContent></Card>;
}

export function PaymentRefunds({ refunds }: { refunds: PaymentRefund[] }) {
  return <Card><CardHeader><div className="flex items-center gap-2"><History className="h-5 w-5 text-primary" /><div><CardTitle>Refunds</CardTitle><p className="mt-1 text-sm text-muted-foreground">Refund state and provider references returned by Payment Service.</p></div></div></CardHeader><CardContent className="p-0">{refunds.length === 0 ? <p className="p-5 text-sm text-slate-500">No refunds.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><caption className="sr-only">Payment refunds</caption><thead><tr className="border-y border-slate-100 text-xs font-semibold uppercase tracking-[0.1em] text-slate-400"><th className="px-5 py-3">Refund ID</th><th className="px-3 py-3 text-right">Amount</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Reason</th><th className="px-3 py-3">Provider refund ID</th><th className="px-3 py-3">Created</th><th className="px-3 py-3">Completed</th></tr></thead><tbody>{refunds.map((refund) => <tr className="table-row" key={refund.id}><td className="px-5 py-4 font-mono text-xs text-slate-700">{refund.id}</td><td className="px-3 py-4 text-right text-sm font-semibold text-slate-800">{formatCurrency(refund.amount, refund.currency)}</td><td className="px-3 py-4"><RefundStatusBadge status={refund.status} /></td><td className="px-3 py-4 max-w-[18rem] text-sm text-slate-600">{refund.reason ?? "—"}</td><td className="px-3 py-4 font-mono text-xs text-slate-600">{refund.providerRefundId ?? "—"}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(refund.createdAt)}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(refund.completedAt)}</td></tr>)}</tbody></table></div>}</CardContent></Card>;
}
