import Link from "next/link";
import { Eye } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { OrderActions } from "@/components/orders/order-actions";
import { OrderPagination } from "@/components/orders/order-pagination";
import { OrderStatusBadge } from "@/components/orders/order-status-badge";
import { CustomerReference } from "@/components/customers/customer-reference";
import type { OrderSummary } from "@/lib/api/order/types";
import type { PageResponse } from "@/lib/types";
import { formatCurrency, formatDate } from "@/lib/utils";

export function OrderTable({ page, onPageChange, onPageSizeChange, pageSize }: { page: PageResponse<OrderSummary>; onPageChange: (page: number) => void; onPageSizeChange: (size: number) => void; pageSize: number }) {
  return <Card className="overflow-hidden"><CardContent className="p-0"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[940px] text-left"><caption className="sr-only">Orders</caption><thead><tr className="border-y border-slate-100 text-xs font-semibold uppercase tracking-[0.1em] text-slate-400"><th className="px-5 py-3">Order</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Total</th><th className="px-3 py-3">Currency</th><th className="px-3 py-3">Created</th><th className="px-3 py-3">Updated</th><th className="px-3 py-3 text-right">Actions</th></tr></thead><tbody>{page.content.map((order) => <tr className="table-row" key={order.id}><td className="px-5 py-4"><Link href={`/orders/${order.id}`} className="font-mono text-sm font-semibold text-primary hover:underline">{order.orderNumber}</Link><p className="mt-1 font-mono text-[10px] text-slate-400">{order.id}</p></td><td className="px-3 py-4"><CustomerReference customerId={order.customerId} /></td><td className="px-3 py-4"><OrderStatusBadge status={order.status} /></td><td className="px-3 py-4 text-right text-sm font-semibold text-slate-800">{formatCurrency(order.totalAmount, order.currency)}</td><td className="px-3 py-4 text-sm text-slate-500">{order.currency}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(order.createdAt)}</td><td className="px-3 py-4 text-sm text-slate-600">{formatDate(order.updatedAt)}</td><td className="px-3 py-4"><div className="flex justify-end gap-2"><Link href={`/orders/${order.id}`} className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-semibold text-primary hover:bg-blue-50"><Eye className="h-4 w-4" />View</Link><OrderActions order={order} /></div></td></tr>)}</tbody></table></div><div className="divide-y divide-slate-100 md:hidden">{page.content.map((order) => <article className="space-y-4 p-5" key={order.id}><div className="flex items-start justify-between gap-3"><div><Link href={`/orders/${order.id}`} className="font-mono text-sm font-semibold text-primary hover:underline">{order.orderNumber}</Link><p className="mt-1 text-xs text-slate-400">{formatDate(order.createdAt)}</p></div><OrderStatusBadge status={order.status} /></div><CustomerReference customerId={order.customerId} /><div className="flex items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.1em] text-slate-400">Total</p><p className="mt-1 text-lg font-bold text-slate-900">{formatCurrency(order.totalAmount, order.currency)}</p></div><div className="flex gap-2"><Link href={`/orders/${order.id}`} className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-semibold text-primary hover:bg-blue-50"><Eye className="h-4 w-4" />View</Link><OrderActions order={order} /></div></div></article>)}</div><OrderPagination page={page} pageSize={pageSize} onPageChange={onPageChange} onPageSizeChange={onPageSizeChange} /></CardContent></Card>;
}
